"""Integration tests: zone-rule BUILDER vs reference Python generator.

The heart of Session 3 (auto-hosting): the compiled Netelpro builder
(builders/zone_rule_builder.sl) must produce byte-identical rule source
to the Python reference generator -- except the provenance line, which
honestly names the builder as author.

Also verifies: the builder's product compiles natively as a gate rule,
makes correct decisions (including the src_backup component-wise trap),
and that the adapter enforces capacity + fail-safe behavior.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

pytest.importorskip("llvmlite")

from netelpro.rule_filter import RuleBuilder, RuleFilter  # noqa: E402

_ADAPTER_PATH = _REPO_ROOT / "builders" / "zone_builder_adapter.py"
_SPEC = importlib.util.spec_from_file_location("zone_builder_adapter", _ADAPTER_PATH)
adapter = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(adapter)  # type: ignore[union-attr]

# Load the reference Python generator DIRECTLY by path (cross-repo, by design:
# byte-parity against the real source of truth is the integration contract).
_GEN_PATH = Path(
    r"C:\Users\Jona\Desktop\FinalFront\src\neuromancer\domains\agentic\application\zone_rule_generator.py"
)
_gen_spec = importlib.util.spec_from_file_location("zone_rule_generator_ref", _GEN_PATH)
gen_mod = importlib.util.module_from_spec(_gen_spec)
_gen_spec.loader.exec_module(gen_mod)  # type: ignore[union-attr]


def _strip_provenance(source: str) -> str:
    """Remove the first header line (provenance) for byte-parity comparison."""
    lines = source.split("\n")
    return "\n".join(lines[1:])


def _canon(roots: list[str]) -> list[str]:
    """Host-side canonicalization (the adapter's contract: pre-canonicalized args)."""
    return sorted({str(Path(r).resolve()).replace("\\", "/").lower() for r in roots})


def _builder_provenance(source: str) -> str:
    """Swap the reference provenance line for the builder's (honest authorship)."""
    return source.replace(
        "; Netelpro zone policy rule generated by zone_rule_generator.py.",
        "; Netelpro zone policy rule generated by the zone-rule BUILDER (Netelpro v0.5 auto-hosting).",
    )


CONFIGS = [
    (["c:/p/.env"], ["c:/p/workspace"], ["c:/p/src"]),
    (["c:/p/.env", "c:/p/data/keys.enc"], ["c:/p/docs", "c:/p/workspace"], ["c:/p/skills", "c:/p/src"]),
    ([], ["c:/p/workspace"], ["c:/p/src"]),
    (["c:/p/.env"], [], []),
    ([], [], []),
    (["c:/p/secret/"], ["c:/p/workspace/"], ["c:/p/src/"]),
    (["c:/p/quote\"dir"], ["c:/p/back\\slash"], ["c:/p/tab\tdir"]),
]


def test_builder_bytes_identical_to_reference_generator() -> None:
    """Every config: builder output == reference generator output modulo provenance."""
    for red, green, yellow in CONFIGS:
        red, green, yellow = _canon(red), _canon(green), _canon(yellow)
        built = adapter.build_zone_rule_source(red, green, yellow)
        assert built is not None, f"builder failed on {red=} {green=} {yellow=}"
        expected = gen_mod.generate_zone_rule_source(
            red_paths=red, green_roots=green, yellow_roots=yellow
        )
        assert _strip_provenance(built) == _strip_provenance(expected), (
            f"MISMATCH for {red=} {green=} {yellow=}"
        )
        # Provenance line honestly names the builder:
        assert "generated by the zone-rule BUILDER" in built.split("\n")[0]


def test_capacity_beyond_6_rejected() -> None:
    """7 roots in a zone: adapter returns None (host-side enforcement, no truncation)."""
    red7 = [f"c:/p/secret{i}" for i in range(7)]
    built = adapter.build_zone_rule_source(red7, ["c:/p/ws"], ["c:/p/src"])
    assert built is None


def test_six_roots_exactly_fits() -> None:
    """6 roots per zone: the v2 capacity boundary works (36 args)."""
    red6 = [f"c:/p/s{i}" for i in range(6)]
    green6 = [f"c:/p/g{i}" for i in range(6)]
    yellow6 = [f"c:/p/y{i}" for i in range(6)]
    built = adapter.build_zone_rule_source(red6, green6, yellow6)
    assert built is not None
    expected = gen_mod.generate_zone_rule_source(
        red_paths=red6, green_roots=green6, yellow_roots=yellow6
    )
    assert _strip_provenance(built) == _strip_provenance(expected)


def test_built_rule_compiles_and_decides() -> None:
    """The builder's product is a real gate: compiles natively and classifies."""
    red = ["c:/app/.env", "c:/app/routes.py"]
    green = ["c:/app/workspace", "c:/app/docs", "c:/app/downloads", "c:/app/data/tasks.json"]
    yellow = ["c:/app/skills", "c:/app/src", "c:/app/tests"]
    built = adapter.build_zone_rule_source(red, green, yellow)
    assert built is not None
    gate = RuleFilter(built)
    assert gate.decide("c:/app/.env", 1) is True
    assert gate.decide("c:/app/workspace", 2) is True
    assert gate.decide("c:/app/data/tasks.json", 2) is True
    assert gate.decide("c:/app/src", 3) is True
    assert gate.decide("c:/app/src/main.py", 3) is True
    # The src_backup component-wise trap:
    assert gate.decide("c:/app/src_backup/main.py", 3) is False
    # RED does not leak into green/yellow queries:
    assert gate.decide("c:/app/.env", 2) is False
    assert gate.decide("c:/app/.env", 3) is False


def test_builder_program_itself_compiles() -> None:
    """Sanity: the builder .sl compiles via RuleBuilder directly."""
    src = (_REPO_ROOT / "builders" / "zone_rule_builder.sl").read_text(encoding="utf-8")
    builder = RuleBuilder(src)
    assert builder._arity == 36


def test_verify_build_parity_adapter_configs() -> None:
    """Native vs interpreter parity for all adapter configs."""
    src = (_REPO_ROOT / "builders" / "zone_rule_builder.sl").read_text(encoding="utf-8")
    builder = RuleBuilder(src)
    cases = []
    for red, green, yellow in CONFIGS:
        red, green, yellow = _canon(red), _canon(green), _canon(yellow)
        args = adapter._pack_zone(red) + adapter._pack_zone(green) + adapter._pack_zone(yellow)
        expected = gen_mod.generate_zone_rule_source(
            red_paths=red, green_roots=green, yellow_roots=yellow
        )
        cases.append((tuple(args), _builder_provenance(expected)))
    mismatches = builder.verify_build(cases)
    assert mismatches == [], f"parity mismatches: {mismatches}"