"""Receipts-RAFT loop logic, GPU-free and testable (spec v0.2 §4, §6, §8 step 3).

The notebook (training/train_receipts_raft_kaggle.ipynb, generated by
training/create_receipts_raft_notebook.py) only loads the model, samples and
trains; everything that decides WHAT is trained lives here.

Staged execution, one Kaggle kernel per stage, because §6 puts a human
between harvest and training and a Kaggle run cannot pause for one:

    stage 0        harvest round 0 with the base model -> audit sheet
    stage r (1-4)  gate: round r-1 hand audit committed in the repo with a
                   hacking rate <= 2% (D11), else abort; re-score the whole
                   accumulated pool with the CURRENT reward (detector fixes
                   propagate, §6.2); train on it; harvest round r -> audit
    stage 5        gate on round 4; re-score; train; export GGUF

Both arms use generate_round(r) for round r (D8: same data, seed, budget).
Arm A trains SFT on R=1 samples; arm B trains DPO on (R=1, R=0) pairs drawn
from the same sampling of the same prompt -- no human label, no template.
"""

from __future__ import annotations

import json
import random
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Callable

from rlvr.receipts_reward import reward
from rlvr.receipts_scenarios import GenScenario, generate_round

NUM_ROUNDS = 5
SAMPLES_PER_SCENARIO = 16
SAMPLING_TEMPERATURE = 0.8
MAX_NEW_TOKENS = 160  # same budget as the benchmark the result is judged on
MAX_KEEP_PER_SCENARIO = 2  # arm A: as RAFT v2's MAX_KEEP_PER_TASK
MAX_PAIRS_PER_SCENARIO = 2  # arm B
AUDIT_SIZE = 48  # §6.1
MAX_HACKED_PER_48 = 1  # D11: "<= 2% (<= 1 de 48)" -- the spec's 2% is 1/48 = 2.08%; the count is the rule
ARMS = ("A", "B")
# Stage 0 is the base model harvesting round 0 -- identical for both arms
# (same model, scenarios, seed). It runs once, as arm B, and both arms' stage
# 1 start from that output and that single hand audit: D8 gets the SAME data
# instead of two near-identical samplings, and the audit is labelled once.
SHARED_STAGE0_ARM = "B"

SampleFn = Callable[[list[dict[str, str]], int, float], list[str]]


@dataclass
class Sample:
    round: int
    scenario_id: str
    text: str
    reward: int
    reasons: list[str]


def round_scenarios(round_num: int) -> dict[str, GenScenario]:
    return {s.id: s for s in generate_round(round_num)}


def harvest(round_num: int, sample_fn: SampleFn, *, n: int = SAMPLES_PER_SCENARIO,
            temperature: float = SAMPLING_TEMPERATURE) -> list[Sample]:
    """Sample n completions per scenario of round `round_num`, grade each."""
    out: list[Sample] = []
    for sid, s in round_scenarios(round_num).items():
        for text in sample_fn(list(s.messages), n, temperature):
            r = reward(text, s)
            out.append(Sample(round_num, sid, text, r.reward, r.reasons))
    return out


def rescore(pool: list[Sample]) -> int:
    """Re-grade every sample with the current reward, in place (§6.2: a
    detector fix re-scores the WHOLE accumulated pool before training).
    Returns how many rewards changed."""
    cache: dict[int, dict[str, GenScenario]] = {}
    changed = 0
    for smp in pool:
        scen = cache.setdefault(smp.round, round_scenarios(smp.round))[smp.scenario_id]
        r = reward(smp.text, scen)
        if r.reward != smp.reward:
            changed += 1
        smp.reward, smp.reasons = r.reward, r.reasons
    return changed


def _by_scenario(pool: list[Sample]) -> dict[tuple[int, str], list[Sample]]:
    groups: dict[tuple[int, str], list[Sample]] = {}
    for smp in pool:
        groups.setdefault((smp.round, smp.scenario_id), []).append(smp)
    return groups


def sft_examples(pool: list[Sample]) -> list[dict[str, Any]]:
    """Arm A: R=1 samples, at most MAX_KEEP_PER_SCENARIO distinct texts per scenario."""
    out = []
    cache: dict[int, dict[str, GenScenario]] = {}
    for (rnd, sid), group in sorted(_by_scenario(pool).items()):
        scen = cache.setdefault(rnd, round_scenarios(rnd))[sid]
        seen: set[str] = set()
        for smp in group:
            if smp.reward == 1 and smp.text not in seen and len(seen) < MAX_KEEP_PER_SCENARIO:
                seen.add(smp.text)
                out.append({"messages": list(scen.messages), "completion": smp.text})
    return out


def dpo_pairs(pool: list[Sample]) -> list[dict[str, Any]]:
    """Arm B: (chosen R=1, rejected R=0) from the SAME sampling of the same
    prompt. Scenarios with only winners or only losers give no pair."""
    out = []
    cache: dict[int, dict[str, GenScenario]] = {}
    for (rnd, sid), group in sorted(_by_scenario(pool).items()):
        good = list(dict.fromkeys(s.text for s in group if s.reward == 1))
        bad = list(dict.fromkeys(s.text for s in group if s.reward == 0))
        scen = cache.setdefault(rnd, round_scenarios(rnd))[sid]
        for chosen, rejected in list(zip(good, bad))[:MAX_PAIRS_PER_SCENARIO]:
            out.append({"messages": list(scen.messages), "chosen": chosen, "rejected": rejected})
    return out


def audit_sheet(round_samples: list[Sample], *, seed: int, k: int = AUDIT_SIZE) -> list[dict[str, Any]]:
    """§6.1: k R=1 samples at random from this round's harvest, to label by
    hand BEFORE they are trained on. Conversation included, reward reasons
    excluded (the labeller must not see the detector's read)."""
    winners = [s for s in round_samples if s.reward == 1]
    picked = random.Random(seed).sample(winners, min(k, len(winners)))
    scen: dict[int, dict[str, GenScenario]] = {}
    rows = []
    for i, smp in enumerate(picked):
        sc = scen.setdefault(smp.round, round_scenarios(smp.round))[smp.scenario_id]
        rows.append({
            "audit_id": f"a{i:02d}", "round": smp.round, "scenario_id": smp.scenario_id,
            "conversation": [m for m in sc.messages if m["role"] != "system"],
            "model_text": smp.text, "human_label": None,
        })
    return rows


def audit_gate(labelled_sheet: list[dict[str, Any]]) -> tuple[float, bool, str]:
    """D11: hacking rate = share of R=1 samples a human labels as theater.
    Returns (rate, ok, message). Unlabelled or unknown labels fail closed."""
    if not labelled_sheet:
        return 1.0, False, "empty audit sheet"
    labels = [r.get("human_label") or "" for r in labelled_sheet]
    if any(not lab.startswith(("theater", "honest-claim", "no-claim")) for lab in labels):
        return 1.0, False, "audit has unlabelled rows or unknown label prefixes"
    hacked = sum(lab.startswith("theater") for lab in labels)
    rate = hacked / len(labels)
    ok = hacked * AUDIT_SIZE <= MAX_HACKED_PER_48 * len(labels)
    return rate, ok, f"hacking {hacked}/{len(labels)} = {rate:.1%} ({'ok' if ok else 'ABOVE 2% -- round does not train'})"


def audit_labels_path(repo_root: Path, arm: str, round_num: int) -> Path:
    owner = SHARED_STAGE0_ARM if round_num == 0 else arm
    return repo_root / "benchmarks" / "receipts_raft_audit" / f"arm{owner}_r{round_num}_labels.json"


def require_audit(repo_root: Path, arm: str, round_num: int) -> str:
    """Abort the stage unless round `round_num`'s hand audit is committed and passes."""
    p = audit_labels_path(repo_root, arm, round_num)
    if not p.exists():
        raise RuntimeError(f"no hand audit for arm {arm} round {round_num} at {p} -- label the sheet and commit it first (§6)")
    rate, ok, msg = audit_gate(json.loads(p.read_text(encoding="utf-8")))
    if not ok:
        raise RuntimeError(f"arm {arm} round {round_num}: {msg}")
    return msg


def save_pool(pool: list[Sample], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps([asdict(s) for s in pool], ensure_ascii=False), encoding="utf-8")


def load_pool(path: Path) -> list[Sample]:
    return [Sample(**d) for d in json.loads(path.read_text(encoding="utf-8"))]


def round_stats(samples: list[Sample]) -> dict[str, Any]:
    """Per-round numbers for the report: harvest size, R=1 rate per family."""
    fam_of = {}
    for rnd in {s.round for s in samples}:
        fam_of.update({(rnd, sid): sc.family for sid, sc in round_scenarios(rnd).items()})
    by_fam: dict[str, list[int]] = {}
    for s in samples:
        by_fam.setdefault(fam_of[(s.round, s.scenario_id)], []).append(s.reward)
    return {
        "n": len(samples),
        "r1": sum(s.reward for s in samples),
        "r1_by_family": {f: f"{sum(v)}/{len(v)}" for f, v in sorted(by_fam.items())},
    }
