; Netelpro zone policy rule generated by the zone-rule BUILDER (Netelpro v0.5 auto-hosting).
; Pure host security gate compiled natively via LLVM.
;
; Parameters:
;   path: Str (canonicalized filesystem path, UTF-8, lowercase, forward slashes)
;   zone: Int (zone rank: 1=RED, 2=GREEN, 3=YELLOW)
;
; Returns:
;   Bool (true if path is a member of the specified zone rank, false otherwise).
;
; Zone Rank Convention:
;   1 = RED    (blocked / critical operations)
;   2 = GREEN  (autonomous operations)
;   3 = YELLOW (proposed / confirmation required)
;
; Trailing Separator Law (Component-wise Containment):
;   Every root is evaluated component-wise using both an exact match (==)
;   and containment under a trailing slash (prefix?), preventing false
;   prefix matches such as 'src_backup' against 'src'.
(defn filter-rule (path zone)
  (if (== zone 1)
      (if (or (== path "c:/users/jona/desktop/finalfront/.env") (or (prefix? path "c:/users/jona/desktop/finalfront/.env/") (or (== path "c:/users/jona/desktop/finalfront/data/api_keys.enc") (or (prefix? path "c:/users/jona/desktop/finalfront/data/api_keys.enc/") (or (== path "c:/users/jona/desktop/finalfront/src/neuromancer/api/container.py") (or (prefix? path "c:/users/jona/desktop/finalfront/src/neuromancer/api/container.py/") (or (== path "c:/users/jona/desktop/finalfront/src/neuromancer/api/routes.py") (or (prefix? path "c:/users/jona/desktop/finalfront/src/neuromancer/api/routes.py/") (or (== path "c:/users/jona/desktop/finalfront/src/neuromancer/domains/telegram") (prefix? path "c:/users/jona/desktop/finalfront/src/neuromancer/domains/telegram/")))))))))) true false)
      (if (== zone 2)
          (if (or (== path "c:/users/jona/desktop/finalfront/data/runtime_params.json") (or (prefix? path "c:/users/jona/desktop/finalfront/data/runtime_params.json/") (or (== path "c:/users/jona/desktop/finalfront/data/tasks.json") (or (prefix? path "c:/users/jona/desktop/finalfront/data/tasks.json/") (or (== path "c:/users/jona/desktop/finalfront/docs") (or (prefix? path "c:/users/jona/desktop/finalfront/docs/") (or (== path "c:/users/jona/desktop/finalfront/downloads") (or (prefix? path "c:/users/jona/desktop/finalfront/downloads/") (or (== path "c:/users/jona/desktop/finalfront/workspace") (prefix? path "c:/users/jona/desktop/finalfront/workspace/")))))))))) true false)
          (if (== zone 3)
              (if (or (== path "c:/users/jona/desktop/finalfront/skills") (or (prefix? path "c:/users/jona/desktop/finalfront/skills/") (or (== path "c:/users/jona/desktop/finalfront/src") (or (prefix? path "c:/users/jona/desktop/finalfront/src/") (or (== path "c:/users/jona/desktop/finalfront/tests") (prefix? path "c:/users/jona/desktop/finalfront/tests/")))))) true false)
              (if (== path "") false false)))))
