; Netelpro zone rule builder program (v2 -- auto-hosting).
; Generates zone-policy filter-rule source text, byte-identical to the
; reference fold in zone_rule_generator.py (except the provenance line,
; which names the builder: this rule is written by the language itself).
;
; CONTRACT & ARCHITECTURE SPECIFICATION:
; 1. Signature & Arity Design:
;    (defn build-rule (re1 rp1 re2 rp2 re3 rp3 re4 rp4 re5 rp5 re6 rp6
;                      ge1 gp1 ge2 gp2 ge3 gp3 ge4 gp4 ge5 gp5 ge6 gp6
;                      ye1 yp1 ye2 yp2 ye3 yp3 ye4 yp4 ye5 yp5 ye6 yp6) ...)
;    Fixed arity 36: 3 zones (RED=1, GREEN=2, YELLOW=3) x 6 root slots x
;    2 forms per root (exact match + trailing-slash prefix).
;    Production config (Neuromancer house): 5 green, 3 yellow, 5 red -> fits.
;
; 2. Host-Side Responsibilities (frontier):
;    - Canonicalization (forward slashes, lowercase, resolve, dedupe, sort).
;    - Pre-escaping for .sl string literals (\\, \", \n, \t).
;    - Trailing-slash computation: exact root and prefix root as separate args.
;    - Sentinel: unused slots receive the empty string "". A real canonicalized
;      root is never empty, so the sentinel is unambiguous.
;    - Capacity enforcement: > 6 roots per zone is rejected host-side
;      (ZoneBuilderError) -- no silent truncation.
;
; 3. Chain Shape (matches the reference fold exactly):
;    For k real roots (sorted), conds c1..c2k fold right-nested:
;      (or c1 (or c2 (or c3 ... (or c(2k-1) c(2k))...)))
;    The LAST sorted root's pair is the innermost (or == prefix?); every
;    earlier root wraps: (or (== path "e") (or (prefix? path "p") REST)).
;    Implemented BACKWARD (slot 6 -> slot 1) with nested lets and a
;    non-recursive helper -- no recursion, no deep-stack risk.
;    Empty zone (all sentinels) -> branch "false".
;
; 4. Output Parity:
;    Byte-identical to the reference generator (header + (defn filter-rule
;    (path zone) ...) + nested or/if chains), except the provenance line.

(defn step-leaf-p (p)
  (let close-paren "\"))"
    (str-cat "\") (prefix? path \"" (str-cat p close-paren))))

(defn step-leaf (e p)
  (let h (str-cat "(or (== path \"" e)
    (let leaf-rest (step-leaf-p p)
      (str-cat h leaf-rest))))

(defn step-node-tail (state)
  (let s (str-cat state "))")
    (str-cat "\") " s)))

(defn step-node-mid (p node-tail)
  (let m (str-cat "\") (or (prefix? path \"" p)
    (str-cat m node-tail)))

(defn step-node (e p state)
  (let h (str-cat "(or (== path \"" e)
    (let node-rest (step-node-mid p (step-node-tail state))
      (str-cat h node-rest))))

(defn step (state e p)
  (if (== e "")
      state
      (if (== state "")
          (step-leaf e p)
          (step-node e p state))))

(defn zone-branch (e1 p1 e2 p2 e3 p3 e4 p4 e5 p5 e6 p6)
  (let s6 (step "" e6 p6)
    (let s5 (step s6 e5 p5)
      (let s4 (step s5 e4 p4)
        (let s3 (step s4 e3 p3)
          (let s2 (step s3 e2 p2)
            (let s1 (step s2 e1 p1)
              (if (== s1 "")
                  "false"
                  (str-cat "(if " (str-cat s1 " true false)"))))))))))

(defn part-tail (y)
  (let p3 "\n          (if (== zone 3)\n              "
    (let p4 "\n              (if (== path \"\") false false)))))\n"
      (let yp4 (str-cat y p4)
        (str-cat p3 yp4)))))

(defn part-mid (g tail-str)
  (let p2 "\n      (if (== zone 2)\n          "
    (let gtail (str-cat g tail-str)
      (str-cat p2 gtail))))

(defn part-head (r g y)
  (let p1 "; Netelpro zone policy rule generated by the zone-rule BUILDER (Netelpro v0.5 auto-hosting).\n; Pure host security gate compiled natively via LLVM.\n;\n; Parameters:\n;   path: Str (canonicalized filesystem path, UTF-8, lowercase, forward slashes)\n;   zone: Int (zone rank: 1=RED, 2=GREEN, 3=YELLOW)\n;\n; Returns:\n;   Bool (true if path is a member of the specified zone rank, false otherwise).\n;\n; Zone Rank Convention:\n;   1 = RED    (blocked / critical operations)\n;   2 = GREEN  (autonomous operations)\n;   3 = YELLOW (proposed / confirmation required)\n;\n; Trailing Separator Law (Component-wise Containment):\n;   Every root is evaluated component-wise using both an exact match (==)\n;   and containment under a trailing slash (prefix?), preventing false\n;   prefix matches such as 'src_backup' against 'src'.\n(defn filter-rule (path zone)\n  (if (== zone 1)\n      "
    (let rest-str (part-mid g (part-tail y))
      (let rrest (str-cat r rest-str)
        (str-cat p1 rrest)))))

(defn build-rule (re1 rp1 re2 rp2 re3 rp3 re4 rp4 re5 rp5 re6 rp6
                  ge1 gp1 ge2 gp2 ge3 gp3 ge4 gp4 ge5 gp5 ge6 gp6
                  ye1 yp1 ye2 yp2 ye3 yp3 ye4 yp4 ye5 yp5 ye6 yp6)
  (let r (zone-branch re1 rp1 re2 rp2 re3 rp3 re4 rp4 re5 rp5 re6 rp6)
    (let g (zone-branch ge1 gp1 ge2 gp2 ge3 gp3 ge4 gp4 ge5 gp5 ge6 gp6)
      (let y (zone-branch ye1 yp1 ye2 yp2 ye3 yp3 ye4 yp4 ye5 yp5 ye6 yp6)
        (part-head r g y)))))